name: Build Windows Release

on:
  push:
    tags:
      - '*'
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole --add-data "data;data" --add-data "sounds;sounds" main.py
          move dist\main.exe ImpuestosPagosTracker.exe

      - name: Create ZIP
        run: Compress-Archive -Path ImpuestosPagosTracker.exe -DestinationPath ImpuestosPagosTracker.zip

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: ImpuestosPagosTracker.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
